[project]
name = "codecrafters-git-python"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "ruff>=0.14.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
